# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: src/crispy-guacamole/
      run: dotnet restore
      
    - name: Build
      working-directory: src/crispy-guacamole/
      run: dotnet build --no-restore
      
    - name: Test
      working-directory: src/crispy-guacamole/
      run: dotnet test --no-build --verbosity normal
      
#     - name: Git Version
#       id: version
#       uses: codacy/git-version@2
#       with:
#         release-branch: main
    - run: dotnet tool install --global GitVersion.Tool 
    - run: dotnet-gitversion /output buildserver
    - run: env
    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_TAG: ${{ steps.version.outputs.version }}
        ASSET_FILE_NAME: ${{ format('{0}_build.zip',steps.version.outputs.version) }}
      run: |
        zip -r9 $ASSET_FILE_NAME ./src/crispy-guacamole/bin/Debug/net6.0/*
        gh release create $RELEASE_TAG $ASSET_FILE_NAME
