# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: src/crispy-guacamole/
      run: dotnet restore
    - name: Build
      working-directory: src/crispy-guacamole/
      run: dotnet build --no-restore
    - name: Test
      working-directory: src/crispy-guacamole/
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      id: upload
      with:
#         name: # optional, default is artifact
        path: src/
    - name: Create GitHub Release
      uses: actions/github-script@v6
      with:
        script: |
          const response = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'pr${{ github.event.push.after }}',
            name: 'Release for PR #${{ github.event.push.after }}',
            body: 'Add release notes or description here'
          });
          console.log(response.data.html_url);
          console.log(response.data.assets_url);
          console.log(steps.upload);
